"""Add phone number to users

Revision ID: 668fb017a20a
Revises: 69b462a80a2b
Create Date: 2022-12-14 11:28:05.561935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668fb017a20a'
down_revision = '69b462a80a2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
