"""Add phone number to users

Revision ID: 69b462a80a2b
Revises: a9a248ebdfc2
Create Date: 2022-12-14 11:27:52.158286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b462a80a2b'
down_revision = 'a9a248ebdfc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
